[package]
name = "ephemeral-rollups-tooling"
version = "0.0.1"
description = "Ephemeral Rollups Tooling"
edition = "2021"

[features]
default = []

[dev-dependencies]
ephemeral-rollups-sdk = "0.0.7"
ephemeral-rollups-bridge = { path = "../ephemeral-rollups-bridge" }

async-trait = "0.1.73"

solana-sdk = "1.18.21"
solana-client = "1.18.21"
solana-program-test = "1.18.21"

spl-token = "4.0"
spl-associated-token-account = "2.1"

tokio = { version = "1.0.0", features = ["macros"] }
